dataset: mnist
batch_size: 16
img_size: 32
img_channels: 1
unet_schedule: [64, 32, 64, 128, 64, 128, 256, 512, 1024]
epochs: 20
datasets_path: "../../../Datasets"
checkpoints_path: "../../../Checkpoints"
total_noising_steps: 300
model_name: ddpm2
skip_steps: 20
number_of_samples_generated: 1
